# GitHub Pages Configuration
include:
  - _headers
  - _redirects

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .bundle

# Include files
include:
  - .htaccess
  - _headers
  - _redirects
  - robots.txt